// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAl3NkZGFAnj5fwHHopJL3XxMCcDKw01A',
    appId: '1:849745755586:web:1c58d05d1739c5b0946a5b',
    messagingSenderId: '849745755586',
    projectId: 'carcleanplus-1',
    authDomain: 'carcleanplus-1.firebaseapp.com',
    storageBucket: 'carcleanplus-1.appspot.com',
    measurementId: 'G-GKE6R8FPPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ3Da6J5KL7RIT2D3MgMmfSWmFkQ_4E6o',
    appId: '1:849745755586:android:58899c75b3f1e1c2946a5b',
    messagingSenderId: '849745755586',
    projectId: 'carcleanplus-1',
    storageBucket: 'carcleanplus-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGZmsG_PFX-10-pIBndMOio0sKi3Km5GA',
    appId: '1:849745755586:ios:1666761261b4aa34946a5b',
    messagingSenderId: '849745755586',
    projectId: 'carcleanplus-1',
    storageBucket: 'carcleanplus-1.appspot.com',
    iosBundleId: 'com.example.carCleanUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGZmsG_PFX-10-pIBndMOio0sKi3Km5GA',
    appId: '1:849745755586:ios:1666761261b4aa34946a5b',
    messagingSenderId: '849745755586',
    projectId: 'carcleanplus-1',
    storageBucket: 'carcleanplus-1.appspot.com',
    iosBundleId: 'com.example.carCleanUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAl3NkZGFAnj5fwHHopJL3XxMCcDKw01A',
    appId: '1:849745755586:web:6d8ba1c2fba218e0946a5b',
    messagingSenderId: '849745755586',
    projectId: 'carcleanplus-1',
    authDomain: 'carcleanplus-1.firebaseapp.com',
    storageBucket: 'carcleanplus-1.appspot.com',
    measurementId: 'G-C0KPVXRE83',
  );
}
